@startuml Architecture
skinparam linetype polyline
skinparam shadowing false
skinparam rectangle {
  BackgroundColor<<Frontend>> #ADD8E6
  BackgroundColor<<Backend>> #99c4ad
  BorderColor black
  BorderStyle dashed
}

node "Device"
node "Telegram"

package "Frontend" <<Frontend>> {
  artifact "UI Client"
}

package "Backend" <<Backend>> {
  package "Model" {
    artifact "Alerts Engine"
    artifact "DB backend"
    artifact "Cache"
    artifact "ICMP poller"
    artifact "Ansible poller"
    artifact "Facts backend"
    artifact "Syslog backend"
    artifact "Poller"
    
  }

  package "Controller" {
    artifact "HTTP/Websocket API (Rocket)"
    node "DB Drivers" {
      artifact "Psycopg Driver"
      artifact "InfluxDB Driver"
    }
  }

  
  package "External Services" {
    node "rsyslogd (Docker)" {
      artifact "rsyslogd"
    }
    node "Postgres DB (Docker)" {
      database "Postgres"
    }
    node "InfluxDB (Docker)" {
      database "InfluxDB"
    }
  }
}

"Facts backend" -up-> "DB backend"
"Facts backend" --> "Poller"

"ICMP poller" --> "Facts backend"
"Ansible poller" --> "Facts backend" 

"Cache" <--> "DB backend"
"Cache" <--> "Alerts Engine"

"HTTP/Websocket API (Rocket)" --> "UI Client"
"Cache" <--> "HTTP/Websocket API (Rocket)"
"Alerts Engine" <-> "HTTP/Websocket API (Rocket)"
"Alerts Engine" -up-> "Telegram"
"Syslog backend" <-- "rsyslogd"
"Psycopg Driver" --> "Postgres"
"InfluxDB Driver" --> "InfluxDB"
"Facts backend" --> "Cache"
"Syslog backend" --> "Cache"
"DB backend" -right-> "DB Drivers" 

'Device --up--> "rsyslogd"
Device <-up-> "Poller"

' Layout
"Model" .[hidden]left.> "External Services"
"Model" .[hidden]left.> "Controller"
  "Syslog backend" .[hidden]down.> "Facts backend"
  "Syslog backend" -[hidden]-> "DB backend"
  "Syslog backend" .[hidden]up.> "Cache"
  "Cache" .[hidden]up.> "Alerts Engine"
"Controller" .[hidden]down.> "External Services"
  "HTTP/Websocket API (Rocket)" .[hidden]down.> "DB Drivers"
  "rsyslogd (Docker)" .[hidden]right.> "Postgres DB (Docker)"


@enduml