@startuml
nwdiag {

    network LAN {
        address = "x.x.x.x";

        Bridge
    }

    Bridge

    network docker0 {
        address = "172.16.x.x"

        aegis-backend [];
        postgres_db;
        influx_db;
        rsyslog;

        Bridge
    }
}

@enduml
