@startuml realTimeAlerts

actor "Usuario" as User
box "Frontend" #ffdcdcff
boundary "UI" as UI
end box

' Define controller and model lifelines
' Backend
box "Controller" #ADD8E6
control "WebSocket" as WebSocket
end box

box "Model" #99c4ad
boundary "Fact\nGathering" as FactGatheringBackend
entity "Syslog\nBackend" as SyslogBackend
entity "Alert\nBackend" as AlertBackend
Database "Database" as Database
end box

== Subscription ==
User -> UI : Inicio
UI -> WebSocket : registro
WebSocket -> AlertBackend : register_listener(queue)

== Fact event loop ==
loop Corutine
    FactGatheringBackend -> AlertBackend : eval_facts(queue)
    AlertBackend -> AlertBackend : __eval_rules()
    AlertBackend -> AlertBackend : raise_alert()
    AlertBackend -> Database : insert_alert(AlertEvent)
    Database --> AlertBackend : alert_id
    AlertBackend -> WebSocket : notify(alert)
end

== Syslog event loop ==
loop Corutine
    FactGatheringBackend -> AlertBackend : eval_facts(queue)
    AlertBackend -> AlertBackend : __eval_rules()
    AlertBackend -> AlertBackend : raise_alert()
    AlertBackend -> Database : insert_alert(AlertEvent)
    Database --> AlertBackend : alert_id
    AlertBackend -> WebSocket : notify(alert)
end
@enduml
