@startuml TableViewer
actor "User" as User

' Frontend
box "Frontend" #99c4ad
participant "TrinaGrid Table" as TrinaGrid
participant "StateNotifier / Provider" as StateProvider
participant "WebSocketChannel" as WebSocket
end box

' Backend
box "Backend" #LightBlue
  participant "WebSocket" as BackendWS
end box

== Carga inicial ==
User -> TrinaGrid: Mostrar la tabla con filas temporales
TrinaGrid -> StateProvider: Solicitud de conteo de filas
StateProvider -> WebSocket : [Set filters]\n[Request rowCount]
WebSocket -> BackendWS: [Set filters]\n[Request rowCount]
BackendWS --> WebSocket: rowCount
WebSocket --> StateProvider: rowCount
StateProvider --> TrinaGrid: rowCount
TrinaGrid -> TrinaGrid: Creación de filas con efecto shimmer\npara simular la carga

== Petición inicial de datos ==
TrinaGrid -> StateProvider: Petición de datos para las filas visibles
StateProvider -> WebSocket: Petición de filas 0..N
WebSocket -> BackendWS: Petición de filas 0..N
BackendWS --> WebSocket: Stream de mensajes (row 0..N)
WebSocket -> StateProvider: Emisión incremental de filas
StateProvider -> StateProvider: Filas se colocan en Buffer\nEl buffer se vacía cada 100ms
StateProvider --> TrinaGrid: Actualizar las filas cuando\nse saquen los datos del buffer
TrinaGrid -> TrinaGrid: Reemplazo de las filas con shimmer\nPor los datos reales

== Scrolling ==
User -> TrinaGrid: Desplazamiento hasta abajo
TrinaGrid -> StateProvider: Petición de siguientes filas
StateProvider -> WebSocket: Petición de siguientes filas
WebSocket -> BackendWS: Petición de filas M..M+N
BackendWS --> WebSocket: Stream de mensajes (rows M..M+N)
WebSocket -> StateProvider: Emisión incremental de filas
StateProvider -> StateProvider: Buffer & vaciado
StateProvider --> TrinaGrid: Insersión de filas
TrinaGrid -> TrinaGrid: Reemplazo de filas con shimmer
@enduml