@startuml syslogDatabase
skinparam linetype ortho

entity SystemEvents {
  * ID : INTEGER <<PK>>
  Facility : INTEGER
  Priority : INTEGER
  FromHost : TEXT
  InfoUnitID : INTEGER
  ReceivedAt : TIMESTAMP
  DeviceReportedTime : TIMESTAMP
  SysLogTag : TEXT
  ProcessID : TEXT
  Message : TEXT
}

entity SystemEvents_FTS {
  Message : TEXT
  content : "SystemEvents"
  content_rowid : ID
  <<VIRTUAL TABLE using fts5>>
}

entity sqlite_sequence {
  name : TEXT
  seq : INTEGER
  <<AUTOINCREMENT TRACKING>>
}

SystemEvents_FTS --> SystemEvents : content_rowid = ID
sqlite_sequence --> SystemEvents : name = 'SystemEvents'

@enduml
